import type {
  Package,
  AddOn,
  SampleSong,
  ReactionVideo,
  Review,
  FaqItem,
  SiteSettings,
  Coupon,
} from "@/types";

export const defaultSettings: SiteSettings = {
  songsCreated: 0,
  averageRating: 4.9,
  genresSupported: 16,
  countriesServed: 42,
  heroHeadline: "Turn your memories into a song they'll keep forever.",
  heroSupporting:
    "Share your story, choose your sound, and let our creative technology transform your favorite moments into a deeply personal song.",
  trustBadge: "Personalized music made from your memories",
  brandName: "Memories to Melody",
  supportEmail: "hello@memoriestomelody.com",
};

export const seedPackages: Package[] = [
  {
    id: "pkg-essential",
    slug: "essential-song",
    name: "Essential Song",
    description: "A beautifully personalized song with private listening and download.",
    priceCents: 3900,
    currency: "usd",
    features: [
      "Personalized lyrics",
      "One generated song",
      "Private listening page",
      "MP3 download",
      "Standard delivery",
    ],
    revisionCredits: 1,
    includesVideo: false,
    includesWav: false,
    includesLyricVideo: false,
    songVariations: 1,
    deliveryHours: 48,
    stripePriceId: null,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "pkg-premium",
    slug: "premium-story",
    name: "Premium Story",
    description: "More variations, artwork, WAV, and faster delivery.",
    priceCents: 7900,
    currency: "usd",
    features: [
      "Everything in Essential",
      "Multiple song variations",
      "High-quality WAV",
      "Custom cover artwork",
      "Priority delivery",
      "Revision credits",
    ],
    revisionCredits: 3,
    includesVideo: false,
    includesWav: true,
    includesLyricVideo: false,
    songVariations: 3,
    deliveryHours: 24,
    stripePriceId: null,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "pkg-cinematic",
    slug: "cinematic-memory",
    name: "Cinematic Memory",
    description: "The full keepsake: song, lyric video, and photo music video.",
    priceCents: 14900,
    currency: "usd",
    features: [
      "Everything in Premium",
      "Photo-based music video",
      "Multiple visual styles",
      "Full HD download",
      "Extended song duration",
      "Priority processing",
    ],
    revisionCredits: 5,
    includesVideo: true,
    includesWav: true,
    includesLyricVideo: true,
    songVariations: 3,
    deliveryHours: 18,
    stripePriceId: null,
    isActive: false,
    sortOrder: 3,
  },
];

export const seedAddOns: AddOn[] = [
  {
    id: "addon-rush",
    slug: "rush-delivery",
    name: "Rush delivery",
    description: "Move to the front of the creative queue.",
    priceCents: 1900,
    currency: "usd",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "addon-extra-revision",
    slug: "extra-revision",
    name: "Extra revision credit",
    description: "One additional guided revision pass.",
    priceCents: 1500,
    currency: "usd",
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "addon-printed-lyrics",
    slug: "printed-lyrics-card",
    name: "Printable lyric card",
    description: "A beautifully designed PDF of the final lyrics.",
    priceCents: 900,
    currency: "usd",
    isActive: true,
    sortOrder: 3,
  },
];

export const seedSamples: SampleSong[] = [
  {
    id: "sample-1",
    slug: "golden-hour-anniversary",
    title: "Golden Hour With You",
    recipientType: "Partner",
    occasion: "anniversary",
    genre: "acoustic",
    mood: "Romantic",
    vocalType: "Soft female",
    language: "en",
    durationSeconds: 178,
    coverUrl: "/samples/covers/golden-hour.svg",
    audioUrl: "/samples/audio/placeholder-tone.wav",
    lyricsPreview:
      "In the golden hour we found our quiet place / Every glance a promise written on your face...",
  },
  {
    id: "sample-2",
    slug: "birthday-spark",
    title: "Another Lap Around the Sun",
    recipientType: "Best friend",
    occasion: "birthday",
    genre: "pop",
    mood: "Celebratory",
    vocalType: "Female",
    language: "en",
    durationSeconds: 165,
    coverUrl: "/samples/covers/birthday-spark.svg",
    audioUrl: "/samples/audio/placeholder-tone.wav",
    lyricsPreview:
      "Candles catch the laughter in the room / Here's to every chapter still in bloom...",
  },
  {
    id: "sample-3",
    slug: "fathers-steady-hands",
    title: "Steady Hands",
    recipientType: "Father",
    occasion: "fathers-day",
    genre: "country",
    mood: "Nostalgic",
    vocalType: "Warm male",
    language: "en",
    durationSeconds: 192,
    coverUrl: "/samples/covers/steady-hands.svg",
    audioUrl: "/samples/audio/placeholder-tone.wav",
    lyricsPreview:
      "You taught me how to stand when winds get loud / Your steady hands still make me proud...",
  },
  {
    id: "sample-4",
    slug: "new-baby-lullaby",
    title: "Little Light",
    recipientType: "Newborn",
    occasion: "new-baby",
    genre: "soul",
    mood: "Tender",
    vocalType: "Soft female",
    language: "en",
    durationSeconds: 154,
    coverUrl: "/samples/covers/little-light.svg",
    audioUrl: "/samples/audio/placeholder-tone.wav",
    lyricsPreview:
      "Welcome, little light, into our open arms / The world grows softer with your calm...",
  },
  {
    id: "sample-5",
    slug: "wedding-vows-in-melody",
    title: "All Our Tomorrows",
    recipientType: "Spouse",
    occasion: "wedding",
    genre: "rnb",
    mood: "Romantic",
    vocalType: "Duet",
    language: "en",
    durationSeconds: 201,
    coverUrl: "/samples/covers/tomorrows.svg",
    audioUrl: "/samples/audio/placeholder-tone.wav",
    lyricsPreview:
      "I take your hand through every unknown sky / All our tomorrows start tonight...",
  },
  {
    id: "sample-6",
    slug: "gracias-mama",
    title: "Gracias, Mamá",
    recipientType: "Mother",
    occasion: "mothers-day",
    genre: "latin",
    mood: "Emotional",
    vocalType: "Male",
    language: "es",
    durationSeconds: 188,
    coverUrl: "/samples/covers/gracias-mama.svg",
    audioUrl: "/samples/audio/placeholder-tone.wav",
    lyricsPreview:
      "Por cada noche que velaste por mí / Esta canción te abraza sin fin...",
  },
  {
    id: "sample-7",
    slug: "ya-nour-aini",
    title: "يا نور عيني",
    recipientType: "Partner",
    occasion: "wedding",
    genre: "arabic",
    mood: "Romantic",
    vocalType: "Male",
    language: "ar",
    durationSeconds: 117,
    coverUrl: "https://files.kunavo.com/image/2026-08/sF7SbcF5E8KuUu9hVwV7T/lr2m9zlowherxqxflly1.jpg",
    audioUrl: "https://files.kunavo.com/audio/2026-08/sF7SbcF5E8KuUu9hVwV7T/glh08ezrgugu108ka0u7.mp3",
    lyricsPreview: "من أول نظرة عرفت قلبي لقى بيته / في عيونك شفت العمر وكل حكايته...",
  },
  {
    id: "sample-8",
    slug: "everything-you-never-said",
    title: "Everything You Never Said",
    recipientType: "Father",
    occasion: "fathers-day",
    genre: "soul",
    mood: "Emotional",
    vocalType: "Female",
    language: "en",
    durationSeconds: 179,
    coverUrl: "https://files.kunavo.com/image/2026-08/sF7SbcF5E8KuUu9hVwV7T/5vgwtclbo2rftd2p016s.jpg",
    audioUrl: "https://files.kunavo.com/audio/2026-08/sF7SbcF5E8KuUu9hVwV7T/tgcfclsverjftlnzohrc.mp3",
    lyricsPreview:
      "You never were the talking kind, you let your mornings speak / Love was never in your words — it was on my plate...",
  },
  {
    id: "sample-9",
    slug: "petite-etoile",
    title: "Petite Étoile",
    recipientType: "New baby",
    occasion: "new-baby",
    genre: "classical",
    mood: "Tender",
    vocalType: "Soft female",
    language: "fr",
    durationSeconds: 133,
    coverUrl: "https://files.kunavo.com/image/2026-08/sF7SbcF5E8KuUu9hVwV7T/uc308mti2p86r5vbu4oa.jpg",
    audioUrl: "https://files.kunavo.com/audio/2026-08/sF7SbcF5E8KuUu9hVwV7T/9a9zyk3sqtyxx01offp6.mp3",
    lyricsPreview: "Ferme tes yeux, petite étoile / La lune veille sur ton sommeil...",
  },
  {
    id: "sample-10",
    slug: "still-with-me",
    title: "Still With Me",
    recipientType: "Grandmother",
    occasion: "memorial",
    genre: "gospel",
    mood: "Spiritual",
    vocalType: "Choir blend",
    language: "en",
    durationSeconds: 169,
    coverUrl: "https://files.kunavo.com/image/2026-08/sF7SbcF5E8KuUu9hVwV7T/h50gsku3wagx0lqkg2vs.jpg",
    audioUrl: "https://files.kunavo.com/audio/2026-08/sF7SbcF5E8KuUu9hVwV7T/pplkfxtn1se2dozwjl94.mp3",
    lyricsPreview: "I still hear your voice in the morning / Soft as the light through the door...",
  },
  {
    id: "sample-11",
    slug: "tassel-to-the-left",
    title: "Tassel to the Left",
    recipientType: "Son",
    occasion: "graduation",
    genre: "hip-hop",
    mood: "Uplifting",
    vocalType: "Male",
    language: "en",
    durationSeconds: 108,
    coverUrl: "https://files.kunavo.com/image/2026-08/sF7SbcF5E8KuUu9hVwV7T/j1z4srwqhbn3m4z85a8u.jpg",
    audioUrl: "https://files.kunavo.com/audio/2026-08/sF7SbcF5E8KuUu9hVwV7T/gvdw0wfrs4vp2bk8p9si.mp3",
    lyricsPreview:
      "Tassel to the left, head up to the sky / This is just the start, watch me learn to fly...",
  },
];

export const seedReactions: ReactionVideo[] = [
  {
    id: "rx-1",
    customerFirstName: "Amelia",
    occasion: "Anniversary",
    quote: "I couldn't stop crying—in the best way.",
    thumbnailUrl: "/samples/reactions/amelia.jpg",
    videoUrl: "/samples/reactions/demo-reaction.mp4",
    isDemo: true,
  },
  {
    id: "rx-2",
    customerFirstName: "Jordan",
    occasion: "Birthday",
    quote: "He played it three times before dinner.",
    thumbnailUrl: "/samples/reactions/jordan.jpg",
    videoUrl: "/samples/reactions/demo-reaction.mp4",
    isDemo: true,
  },
  {
    id: "rx-3",
    customerFirstName: "Priya",
    occasion: "Wedding",
    quote: "Our whole table went quiet, then cheered.",
    thumbnailUrl: "/samples/reactions/priya.jpg",
    videoUrl: "/samples/reactions/demo-reaction.mp4",
    isDemo: true,
  },
  {
    id: "rx-4",
    customerFirstName: "Marcus",
    occasion: "Father's Day",
    quote: "Dad asked for the lyrics on paper.",
    thumbnailUrl: "/samples/reactions/marcus.jpg",
    videoUrl: "/samples/reactions/demo-reaction.mp4",
    isDemo: true,
  },
];

export const seedReviews: Review[] = [
  {
    id: "rev-1",
    customerName: "Elena M.",
    occasion: "Anniversary",
    rating: 5,
    body: "Demo review: The song captured details I forgot I had written down. It felt intimate, not generic.",
    isVerifiedPurchase: true,
    isDemo: true,
    isPublished: true,
    mediaUrl: null,
    reviewedAt: "2026-06-12",
  },
  {
    id: "rev-2",
    customerName: "Noah K.",
    occasion: "Birthday",
    rating: 5,
    body: "Demo review: Setup took under ten minutes. Delivery was clear and the listening page looked beautiful.",
    isVerifiedPurchase: true,
    isDemo: true,
    isPublished: true,
    mediaUrl: null,
    reviewedAt: "2026-05-28",
  },
  {
    id: "rev-3",
    customerName: "Sofia R.",
    occasion: "Memorial",
    rating: 5,
    body: "Demo review: Gentle, respectful, and deeply personal. We played it at the gathering.",
    isVerifiedPurchase: true,
    isDemo: true,
    isPublished: true,
    mediaUrl: null,
    reviewedAt: "2026-04-02",
  },
  {
    id: "rev-4",
    customerName: "Liam T.",
    occasion: "Thank You",
    rating: 4,
    body: "Demo review: Asked for one lyric tweak and the revision landed quickly.",
    isVerifiedPurchase: true,
    isDemo: true,
    isPublished: true,
    mediaUrl: null,
    reviewedAt: "2026-03-18",
  },
];

export const seedFaqs: FaqItem[] = [
  {
    id: "faq-1",
    question: 'How does Memories to Melody work?',
    answer:
      'You tell us your story in a guided five-minute studio — who the song is for, the occasion, the memories that matter, and the sound you love. We turn that into custom lyrics and a fully produced song, then deliver it on a private listening page you can share whenever the moment is right.',
    category: "product",
    sortOrder: 1,
  },
  {
    id: "faq-2",
    question: 'How long until my song is ready?',
    answer:
      'Most songs are ready within 48 hours, and many arrive the same day. Priority delivery on Premium packages moves you to the front of the queue. You can follow progress live from your dashboard, and we email you the moment your song is ready.',
    category: "delivery",
    sortOrder: 2,
  },
  {
    id: "faq-3",
    question: 'What do I need to prepare before I start?',
    answer:
      'Just a few memories. The studio asks simple questions — how you met, an inside joke, a moment you will never forget. Two or three honest details are enough; you do not need to write anything polished. The more specific the memory, the more personal the song feels.',
    category: "product",
    sortOrder: 3,
  },
  {
    id: "faq-4",
    question: 'Can I choose the music style and voice?',
    answer:
      'Yes. Pick from 16+ genres — pop, acoustic, R&B, country, gospel, Arabic, Latin and more — then set the mood and the vocal style: female, male, duet, or choir blend. Not sure? Our guided defaults produce a beautiful result every time.',
    category: "product",
    sortOrder: 4,
  },
  {
    id: "faq-5",
    question: 'Can the song be in another language?',
    answer:
      'Yes — songs can be written and sung in English, French, Spanish, or Arabic. Listen to Gracias Mamá (Spanish), Petite Étoile (French), or يا نور عيني (Arabic) on the examples page to hear how natural they sound.',
    category: "languages",
    sortOrder: 5,
  },
  {
    id: "faq-6",
    question: 'What if I want changes to my song?',
    answer:
      'Every package includes revision credits. From your dashboard you can request changes to lyrics, the pronunciation of names, tempo, mood, or vocals, and we will produce a new version of your song. Most revisions are delivered within 24 hours.',
    category: "revisions",
    sortOrder: 6,
  },
  {
    id: "faq-7",
    question: 'Who owns the song — can I share it online?',
    answer:
      'You receive a lifetime personal-use license: listen, download, gift it, play it at your event, and share it with friends and family, including on your personal social media. Commercial use such as ads or monetized content requires a separate license — just contact us.',
    category: "licensing",
    sortOrder: 7,
  },
  {
    id: "faq-8",
    question: 'How do I give the song as a gift?',
    answer:
      'Every order includes a private listening page with cover artwork, synchronized lyrics, and an optional gift-reveal mode that builds anticipation before the song plays. Share the link by text or email — or play it in person and watch their reaction.',
    category: "gifting",
    sortOrder: 8,
  },
  {
    id: "faq-9",
    question: 'Is my story kept private?',
    answer:
      'Completely. Your answers and any uploaded photos are used only to create your song, and uploads live in private storage. Listening pages are private by default — you decide whether a link is private, password-protected, unlisted, or public, and you can change it anytime.',
    category: "privacy",
    sortOrder: 9,
  },
  {
    id: "faq-10",
    question: 'What is included in each package?',
    answer:
      'Essential includes personalized lyrics, a fully produced song, a private listening page, and an MP3 download. Premium adds multiple song variations, studio-quality WAV, custom cover artwork, priority delivery, and extra revision credits. All are one-time payments — no subscription.',
    category: "pricing",
    sortOrder: 10,
  },
  {
    id: "faq-11",
    question: 'Can I download the song and keep it forever?',
    answer:
      'Yes. Every package includes an MP3 download, and your listening page does not expire. Premium packages add studio-quality WAV files. The song is yours to keep, replay, and pass on.',
    category: "delivery",
    sortOrder: 11,
  },
  {
    id: "faq-12",
    question: 'What if I am not happy with the result?',
    answer:
      'We will make it right. Start with your included revision credits — most concerns are solved with a lyric or vocal change. If a verified quality issue cannot be resolved through revisions, our refund policy applies within 14 days of delivery.',
    category: "refunds",
    sortOrder: 12,
  },
];

export const seedCoupons: Coupon[] = [
  {
    id: "coupon-welcome",
    code: "WELCOME10",
    description: "10% off your first Memories to Melody song",
    percentOff: 10,
    amountOffCents: null,
    currency: "usd",
    maxRedemptions: 1000,
    redemptionCount: 0,
    expiresAt: null,
    isActive: true,
  },
];
